/* Prompt body translations — loaded before script.js */
(function (global) {
  'use strict';

  const EN = {
    role_fg: 'You are a careful C++ developer with experience in the Basler Framegrabber SDK, CoaXPress, Camera Link, DMA buffering, industrial image acquisition, trigger handling, and robust resource cleanup.',
    role_pylon: 'You are a careful C++ developer with experience in the Basler pylon SDK, GenICam, stream grabbers, industrial camera acquisition, trigger handling, buffer management, and robust resource cleanup.',
    deep_mandatory: 'MANDATORY: Extended thinking / deep analysis mode MUST be active for this entire task. Do not skip analysis to save time.',
    deep_priority: 'Prioritize correctness over brevity. Analyze initialization order, buffer lifecycle, error paths, and shutdown before writing code.',
    deep_chatgpt: 'MANDATORY: Enable the deepest reasoning mode available (e.g. extended thinking, deep research, or o-series reasoning). Do not answer quickly.\nBefore any code, produce a structured analysis: SDK headers, board discovery, applet or standardAcquisition loading, buffer/DMA lifecycle, trigger path, error handling, and shutdown order.\nIf deep reasoning is unavailable in this session, state that explicitly at the top and treat every API name as high-risk until verified.\nPrefer complete, compilable modules over fragments. Use markdown sections and numbered steps before the final code block.',
    deep_claude: 'MANDATORY: Use extended thinking / think-deeper mode for the entire task. Do not ship a shallow first-pass implementation.\nIn extended thinking, map Basler Framegrabber SDK concepts to this hardware: initialization, applet or standardAcquisition DLL, DMA buffers, acquisition loop, timeouts, requeue, cleanup.\nIf extended thinking is unavailable, warn prominently that API names and lifecycle order may be wrong.\nDeliver analysis first, then code. Keep assumptions and TODOs inline where documentation is uncertain.',
    deep_copilot: 'MANDATORY: Do not treat this as inline autocomplete. First output a structured implementation plan and SDK concept checklist.\nUse Copilot Chat / agent workflow: identify headers, link libraries, board index, applet file (.dll standardAcquisition or .hap), buffer count, and teardown path before writing functions.\nGenerate full files (source + optional CMakeLists.txt) with consistent naming. Never invent Basler SDK symbols—mark unknowns as TODO with doc lookup hints.\nIf Copilot cannot access Basler documentation, say so and constrain the answer to verified patterns only.',
    deep_cursor: 'MANDATORY: Run in agent mode with extended analysis. Search the workspace and Basler Framegrabber SDK documentation before generating code.\nIdentify: SDK headers, FgLib initialization, board discovery, applet loading (standardAcquisition SingleArea/SingleLine/DualArea/DualLine/QuadArea/QuadLine or VisualApplets .hap), DMA setup, acquisition start/stop, image access, requeue, timeout, cleanup.\nDo not emit implementation code until the above mapping is written in the response.\nPrefer editing existing project files when present; otherwise create minimal reproducible examples with explicit assumptions.',
    deep_generic: 'MANDATORY: Use the most thorough reasoning mode available. Slow down; correctness beats speed.\nProduce a written plan covering SDK initialization, hardware/applet selection, buffers, triggers, acquisition loop, errors, and cleanup before code.\nIf deep reasoning is not available, label the output as best-effort with elevated API and lifecycle risk.\nNever guess Basler SDK function names—use TODO markers tied to official documentation checks.',
    hint_chatgpt: 'Structure the answer with: (1) Assumptions, (2) Architecture, (3) Step-by-step init/acquire/shutdown, (4) Full code, (5) Build/run notes.',
    hint_claude: 'Use clear markdown headings. Separate analysis from code blocks. Call out every uncertain API with TODO.',
    hint_copilot: 'Provide copy-paste-ready files. Include #include list and linker inputs where relevant.',
    hint_cursor: 'Align with workspace conventions. Reference doc paths or headers you inspected.',
    hint_generic: 'Use numbered sections and one consolidated code example at the end.',
    doc_fg_1: 'Use the current Basler Framegrabber SDK documentation.',
    doc_fg_2: 'Verify function names, headers, initialization, board discovery, applet handling, buffer allocation, DMA handling, acquisition start/stop, image access, timeout handling, and cleanup.',
    doc_fg_3: 'Do not invent API calls. If exact API names are unknown, mark them as TODO or assumption.',
    doc_fg_4: 'Do not output a pylon-only solution. pylon may only be mentioned as an optional camera configuration layer if technically appropriate.',
    doc_fg_5: 'The acquisition path must use Basler Framegrabber SDK concepts.',
    doc_pylon_1: 'Use the current Basler pylon SDK documentation.',
    doc_pylon_2: 'Verify function names, headers, device discovery, camera opening, stream grabber behavior, buffer handling, trigger configuration, acquisition start/stop, image access, timeout handling, and cleanup.',
    doc_pylon_3: 'Do not invent API calls. If exact API names are unknown, mark them as TODO or assumption.',
    doc_pylon_4: 'Do not incorrectly use Framegrabber SDK DMA or applet concepts for interface cards or camera interfaces handled through pylon SDK.',
    doc_crosscheck: 'Cross-check every SDK symbol against the latest official documentation before finalizing the answer.',
    not_provided: '(not provided)',
    not_specified: 'not specified',
    none_detected: '(none detected from input text)',
    cfg_sdk_route: 'SDK route',
    cfg_sdk_fg: 'Basler Framegrabber SDK',
    cfg_sdk_pylon: 'Basler pylon SDK',
    cfg_num_cameras: 'Number of cameras',
    cfg_hardware: 'Acquisition hardware',
    cfg_hw_class: 'Hardware class',
    cfg_hw_interface_card: 'interface card (pylon SDK)',
    cfg_hw_acquisition: 'acquisition framegrabber',
    cfg_hw_programmable: 'programmable framegrabber',
    cfg_interface: 'Interface',
    cfg_pixel: 'Pixel type',
    cfg_dma_pixel: 'DMA pixel type',
    cfg_width: 'Image width',
    cfg_height: 'Image height',
    cfg_image_size: 'Image size (W × H)',
    cfg_dma_buffer_size: 'DMA buffer size (W × H)',
    cfg_dma_channels_cam: 'DMA channels',
    cfg_camera_n: 'Camera {n}',
    cfg_camera_type: 'Camera type',
    cfg_dma: 'Number of DMA channels',
    cfg_stream_path: 'Stream grabber / buffer paths (not explicit Framegrabber SDK DMA unless supported)',
    cfg_buffers: 'Host buffer count',
    cfg_trigger: 'Trigger mode',
    cfg_applet_handling: 'Applet handling',
    cfg_std_applet: 'Standard acquisition applet',
    cfg_applet_dll: 'Standard acquisition applet (.dll)',
    cfg_auto_applet: 'Auto-selected standard acquisition applet (.dll)',
    cfg_hap_name: 'VisualApplets .hap name',
    cfg_applet_id: 'Applet identifier',
    cfg_applet_na: 'Applet handling: not applicable (pylon SDK or interface card path)',
    cfg_os: 'Operating system',
    cfg_lang: 'Programming language',
    cfg_style: 'Output style',
    note_interface_pylon: 'Note: The selected interface is typically represented through the Basler pylon SDK, not the Basler Framegrabber SDK.',
    note_interface_card: 'Note: Selected hardware is an interface card. Implement through Basler pylon SDK, not Basler Framegrabber SDK.',
    note_image_dma_diff: 'Note: Sensor image dimensions and DMA buffer dimensions may differ per camera.',
    note_pixel_dma_diff: 'Note: DMA pixel format may differ from the linked camera and from other DMA channels.',
    note_camera_dma_count_diff: 'Note: The number of cameras and the number of DMA channels differ. Map cameras to DMA channels explicitly in the acquisition design.',
    note_mixed_camera_types: 'Note: Cameras use mixed scan types (e.g. area scan and line scan). Configure each camera separately; standard acquisition applets may not map to a single .dll name.',
    std_mixed_camera_types: 'Mixed camera scan types detected. A single standard acquisition applet (SingleArea, DualLine, etc.) cannot be auto-selected. Use a custom VisualApplets .hap design or mark the applet choice as TODO.',
    cfg_num_dma: 'Number of DMA channels',
    cfg_num_stream_paths: 'Number of stream grabber paths',
    cfg_dma_n: 'DMA {n}',
    cfg_host_buffers_dma: 'Host buffers per DMA',
    std_all_dll: 'All Basler framegrabbers can load standard acquisition applets delivered as .dll files (standardAcquisition naming).',
    std_names: 'Common standard applet names: SingleArea, SingleLine, DualArea, DualLine, QuadArea, QuadLine.',
    std_selected: 'Standard acquisition applet: {name}.',
    std_auto_derived: 'On acquisition framegrabbers the standard applet is derived automatically from camera count ({count}) and scan type ({scan}).',
    std_auto_unsupported: 'Camera count {count} does not map to a standard applet name (supported: 1, 2, or 4 cameras). Mark as TODO and verify documentation.',
    imaflex2_single: 'For imaFlex 2 Dual 100, SingleLine is the standard acquisition applet currently available out of the box.',
    imaflex2_dual_hap: 'DualLine or other topologies on imaFlex 2 Dual 100 require a custom VisualApplets design exported as a .hap file.',
    acq_only_dll: 'This is an acquisition framegrabber (not programmable). Use standard acquisition .dll applets; custom .hap applets are not supported on this hardware class.',
    imaflex_both: 'imaFlex boards are programmable framegrabbers: they support both standard acquisition .dll applets and custom VisualApplets .hap designs.',
    hap_load: 'Load a custom VisualApplets applet (.hap) on this programmable framegrabber.',
    hap_name_val: 'VisualApplets .hap name: {name}.',
    scan_area: 'area scan',
    scan_line: 'line scan',
    req_complete: 'Provide a complete {lang} example.',
    req_cmake: 'Include CMakeLists.txt.',
    req_error: 'Implement robust error handling.',
    req_raii: 'Use RAII or clearly structured cleanup.',
    req_timeout: 'Implement timeout handling.',
    req_board: 'Show board discovery.',
    req_std_dll: 'Load the correct standard acquisition .dll applet ({name}).',
    req_std_dll_generic: 'Load the correct standard acquisition .dll applet (SingleArea, SingleLine, DualArea, DualLine, QuadArea, or QuadLine as applicable).',
    req_hap: 'Load the specified VisualApplets .hap applet on the programmable framegrabber.',
    req_applet: 'Handle applet loading or already-loaded applet as configured.',
    req_ports: 'Show camera/port mapping.',
    req_separate: 'Separate camera parameters from framegrabber/applet parameters.',
    req_buffers: 'Show explicit buffer allocation.',
    req_dma: 'Set up DMA/channels.',
    req_device: 'Show device discovery and camera opening.',
    req_stream: 'Configure triggers and stream grabber handling.',
    req_pylon_buf: 'Show appropriate buffer handling for pylon.',
    req_acq: 'Show explicit acquisition start and stop.',
    req_loop: 'Include an acquisition loop for multiple frames.',
    req_image: 'Include an image data access example.',
    req_requeue_fg: 'Include buffer requeueing.',
    req_requeue_pylon: 'Include equivalent buffer handling for pylon.',
    req_shutdown: 'Release all resources on shutdown.',
    req_assumptions: 'List assumptions and TODOs explicitly.',
    req_no_hallucinate: 'Do not hallucinate SDK APIs.',
    req_no_pseudo: 'Do not output pseudocode unless pseudocode was requested.',
    req_no_arch: 'Do not provide only architecture if code was requested.',
    req_multi_sync: 'Include multi-camera synchronization notes where relevant.',
    warning_final: 'Before writing code, list all assumptions. If an exact Basler SDK API name is uncertain, do not invent it. Mark it as TODO and explain what must be checked in the official documentation.'
  };

  const DE = {
    role_fg: 'Sie sind ein sorgfältiger C++-Entwickler mit Erfahrung im Basler Framegrabber SDK, CoaXPress, Camera Link, DMA-Pufferung, industrieller Bilderfassung, Trigger-Handling und robuster Ressourcenfreigabe.',
    role_pylon: 'Sie sind ein sorgfältiger C++-Entwickler mit Erfahrung im Basler pylon SDK, GenICam, Stream Grabbern, industrieller Kameraerfassung, Trigger-Handling, Pufferverwaltung und robuster Ressourcenfreigabe.',
    deep_mandatory: 'PFLICHT: Erweitertes Denken / Deep-Analysis-Modus MUSS für diese gesamte Aufgabe aktiv sein. Überspringen Sie die Analyse nicht, um Zeit zu sparen.',
    deep_priority: 'Korrektheit hat Vorrang vor Kürze. Analysieren Sie Initialisierungsreihenfolge, Puffer-Lebenszyklus, Fehlerpfade und Shutdown, bevor Sie Code schreiben.',
    deep_chatgpt: 'PFLICHT: Aktivieren Sie den tiefsten verfügbaren Reasoning-Modus (z. B. Extended Thinking, Deep Research oder o-series Reasoning). Antworten Sie nicht schnell.\nErstellen Sie vor jedem Code eine strukturierte Analyse: SDK-Header, Board-Erkennung, Applet- oder standardAcquisition-Laden, Puffer/DMA-Lebenszyklus, Trigger-Pfad, Fehlerbehandlung und Shutdown-Reihenfolge.\nWenn Deep Reasoning in dieser Sitzung nicht verfügbar ist, geben Sie das zu Beginn explizit an und behandeln Sie jeden API-Namen als risikobehaftet, bis er verifiziert ist.\nBevorzugen Sie vollständige, kompilierbare Module statt Fragmente. Verwenden Sie Markdown-Abschnitte und nummerierte Schritte vor dem finalen Codeblock.',
    deep_claude: 'PFLICHT: Verwenden Sie Extended Thinking / Think-deeper für die gesamte Aufgabe. Liefern Sie keine oberflächliche Erstimplementierung.\nOrdnen Sie im Extended Thinking Basler Framegrabber SDK-Konzepte dieser Hardware zu: Initialisierung, Applet oder standardAcquisition-DLL, DMA-Puffer, Erfassungsschleife, Timeouts, Requeue, Cleanup.\nWenn Extended Thinking nicht verfügbar ist, warnen Sie deutlich, dass API-Namen und Lebenszyklus-Reihenfolge falsch sein können.\nLiefern Sie zuerst die Analyse, dann den Code. Markieren Sie Annahmen und TODOs inline, wo die Dokumentation unsicher ist.',
    deep_copilot: 'PFLICHT: Behandeln Sie dies nicht als Inline-Autovervollständigung. Geben Sie zuerst einen strukturierten Implementierungsplan und eine SDK-Konzept-Checkliste aus.\nNutzen Sie Copilot Chat / Agent-Workflow: Header, Bibliotheken, Board-Index, Applet-Datei (.dll standardAcquisition oder .hap), Pufferanzahl und Teardown-Pfad identifizieren, bevor Funktionen geschrieben werden.\nErzeugen Sie vollständige Dateien (Quellcode + optional CMakeLists.txt) mit konsistenter Benennung. Erfinden Sie keine Basler-SDK-Symbole—markieren Sie Unbekanntes als TODO mit Dokumentationshinweis.\nWenn Copilot keinen Zugriff auf Basler-Dokumentation hat, sagen Sie das und beschränken Sie die Antwort auf verifizierte Muster.',
    deep_cursor: 'PFLICHT: Im Agent-Modus mit erweiterter Analyse arbeiten. Durchsuchen Sie Workspace und Basler Framegrabber SDK-Dokumentation, bevor Code generiert wird.\nIdentifizieren Sie: SDK-Header, FgLib-Initialisierung, Board-Erkennung, Applet-Laden (standardAcquisition SingleArea/SingleLine/DualArea/DualLine/QuadArea/QuadLine oder VisualApplets .hap), DMA-Setup, Erfassungsstart/-stopp, Bildzugriff, Requeue, Timeout, Cleanup.\nGeben Sie keinen Implementierungscode aus, bevor die obige Zuordnung in der Antwort steht.\nBearbeiten Sie vorhandene Projektdateien, wenn möglich; sonst minimale reproduzierbare Beispiele mit expliziten Annahmen.',
    deep_generic: 'PFLICHT: Verwenden Sie den gründlichsten verfügbaren Reasoning-Modus. Langsamkeit ist akzeptabel; Korrektheit schlägt Geschwindigkeit.\nErstellen Sie einen schriftlichen Plan zu SDK-Initialisierung, Hardware/Applet-Auswahl, Puffern, Triggern, Erfassungsschleife, Fehlern und Cleanup vor dem Code.\nWenn Deep Reasoning nicht verfügbar ist, kennzeichnen Sie die Ausgabe als Best-Effort mit erhöhtem API- und Lebenszyklusrisiko.\nRaten Sie keine Basler-SDK-Funktionsnamen—verwenden Sie TODO-Marker mit Verweis auf offizielle Dokumentation.',
    hint_chatgpt: 'Strukturieren Sie die Antwort: (1) Annahmen, (2) Architektur, (3) Schrittweise Init/Erfassung/Shutdown, (4) Vollständiger Code, (5) Build-/Laufhinweise.',
    hint_claude: 'Verwenden Sie klare Markdown-Überschriften. Trennen Sie Analyse und Codeblöcke. Markieren Sie jede unsichere API mit TODO.',
    hint_copilot: 'Liefern Sie kopierfertige Dateien. Fügen Sie #include-Liste und Linker-Eingaben hinzu, wo relevant.',
    hint_cursor: 'Passen Sie sich an Workspace-Konventionen an. Referenzieren Sie geprüfte Dokumentationspfade oder Header.',
    hint_generic: 'Verwenden Sie nummerierte Abschnitte und ein konsolidiertes Codebeispiel am Ende.',
    doc_fg_1: 'Verwenden Sie die aktuelle Basler Framegrabber SDK-Dokumentation.',
    doc_fg_2: 'Prüfen Sie Funktionsnamen, Header, Initialisierung, Board-Erkennung, Applet-Handling, Pufferallokation, DMA-Handling, Erfassungsstart/-stopp, Bildzugriff, Timeout-Handling und Cleanup.',
    doc_fg_3: 'Erfinden Sie keine API-Aufrufe. Wenn exakte API-Namen unbekannt sind, markieren Sie sie als TODO oder Annahme.',
    doc_fg_4: 'Liefern Sie keine reine pylon-Lösung. pylon darf nur als optionale Kamera-Konfigurationsschicht erwähnt werden, wenn technisch passend.',
    doc_fg_5: 'Der Erfassungspfad muss Basler Framegrabber SDK-Konzepte verwenden.',
    doc_pylon_1: 'Verwenden Sie die aktuelle Basler pylon SDK-Dokumentation.',
    doc_pylon_2: 'Prüfen Sie Funktionsnamen, Header, Geräteerkennung, Kameraöffnung, Stream-Grabber-Verhalten, Puffer-Handling, Trigger-Konfiguration, Erfassungsstart/-stopp, Bildzugriff, Timeout-Handling und Cleanup.',
    doc_pylon_3: 'Erfinden Sie keine API-Aufrufe. Wenn exakte API-Namen unbekannt sind, markieren Sie sie als TODO oder Annahme.',
    doc_pylon_4: 'Verwenden Sie keine Framegrabber-SDK-DMA- oder Applet-Konzepte für Interface-Karten oder Kamera-Interfaces, die über pylon SDK laufen.',
    doc_crosscheck: 'Gleichen Sie jedes SDK-Symbol mit der neuesten offiziellen Dokumentation ab, bevor Sie die Antwort abschließen.',
    not_provided: '(nicht angegeben)',
    not_specified: 'nicht angegeben',
    none_detected: '(keine aus Eingabetext erkannt)',
    cfg_sdk_route: 'SDK-Route',
    cfg_sdk_fg: 'Basler Framegrabber SDK',
    cfg_sdk_pylon: 'Basler pylon SDK',
    cfg_num_cameras: 'Anzahl Kameras',
    cfg_hardware: 'Erfassungshardware',
    cfg_hw_class: 'Hardwareklasse',
    cfg_hw_interface_card: 'Interface-Karte (pylon SDK)',
    cfg_hw_acquisition: 'Acquisition-Framegrabber',
    cfg_hw_programmable: 'Programmierbarer Framegrabber',
    cfg_interface: 'Interface',
    cfg_pixel: 'Pixeltyp',
    cfg_dma_pixel: 'DMA-Pixeltyp',
    cfg_width: 'Bildbreite',
    cfg_height: 'Bildhöhe',
    cfg_image_size: 'Bildgröße (B × H)',
    cfg_dma_buffer_size: 'DMA-Puffergröße (B × H)',
    cfg_dma_channels_cam: 'DMA-Kanäle',
    cfg_camera_n: 'Kamera {n}',
    cfg_camera_type: 'Kameratyp',
    cfg_dma: 'Anzahl DMA-Kanäle',
    cfg_stream_path: 'Stream-Grabber-/Pufferpfade (kein explizites Framegrabber-SDK-DMA, sofern nicht unterstützt)',
    cfg_buffers: 'Anzahl Host-Puffer',
    cfg_trigger: 'Trigger-Modus',
    cfg_applet_handling: 'Applet-Handling',
    cfg_std_applet: 'Standard-Erfassungs-Applet',
    cfg_applet_dll: 'Standard-Erfassungs-Applet (.dll)',
    cfg_auto_applet: 'Automatisch gewähltes Standard-Erfassungs-Applet (.dll)',
    cfg_hap_name: 'VisualApplets-.hap-Name',
    cfg_applet_id: 'Applet-Kennung',
    cfg_applet_na: 'Applet-Handling: nicht anwendbar (pylon SDK oder Interface-Karte)',
    cfg_os: 'Betriebssystem',
    cfg_lang: 'Programmiersprache',
    cfg_style: 'Ausgabestil',
    note_interface_pylon: 'Hinweis: Das gewählte Interface wird typischerweise über das Basler pylon SDK abgebildet, nicht über das Basler Framegrabber SDK.',
    note_interface_card: 'Hinweis: Gewählte Hardware ist eine Interface-Karte. Implementierung über Basler pylon SDK, nicht Basler Framegrabber SDK.',
    note_image_dma_diff: 'Hinweis: Sensorbildabmessungen und DMA-Pufferabmessungen können pro Kamera unterschiedlich sein.',
    note_pixel_dma_diff: 'Hinweis: Das DMA-Pixelformat kann vom verknüpften Kamera-Pixelformat und von anderen DMA-Kanälen abweichen.',
    note_camera_dma_count_diff: 'Hinweis: Die Anzahl der Kameras und die Anzahl der DMA-Kanäle unterscheiden sich. Ordnen Sie Kameras den DMA-Kanälen in der Erfassungsarchitektur explizit zu.',
    note_mixed_camera_types: 'Hinweis: Kameras verwenden gemischte Scan-Typen (z. B. Flächen- und Linienscan). Konfigurieren Sie jede Kamera separat; Standard-Erfassungs-Applets lassen sich möglicherweise keinem einzelnen .dll-Namen zuordnen.',
    std_mixed_camera_types: 'Gemischte Kamera-Scan-Typen erkannt. Ein einzelnes Standard-Erfassungs-Applet (SingleArea, DualLine usw.) kann nicht automatisch gewählt werden. Verwenden Sie ein individuelles VisualApplets-.hap-Design oder markieren Sie die Applet-Wahl als TODO.',
    cfg_num_dma: 'Anzahl DMA-Kanäle',
    cfg_num_stream_paths: 'Anzahl Stream-Grabber-Pfade',
    cfg_dma_n: 'DMA {n}',
    cfg_host_buffers_dma: 'Host-Puffer pro DMA',
    std_all_dll: 'Alle Basler-Framegrabber können Standard-Erfassungs-Applets als .dll-Dateien laden (standardAcquisition-Namensgebung).',
    std_names: 'Übliche Standard-Applet-Namen: SingleArea, SingleLine, DualArea, DualLine, QuadArea, QuadLine.',
    std_selected: 'Standard-Erfassungs-Applet: {name}.',
    std_auto_derived: 'Bei Acquisition-Framegrabbern wird das Standard-Applet automatisch aus Kameraanzahl ({count}) und Scan-Typ ({scan}) abgeleitet.',
    std_auto_unsupported: 'Kameraanzahl {count} lässt sich keinem Standard-Applet-Namen zuordnen (unterstützt: 1, 2 oder 4 Kameras). Als TODO markieren und Dokumentation prüfen.',
    imaflex2_single: 'Für imaFlex 2 Dual 100 ist SingleLine das derzeit verfügbare Standard-Erfassungs-Applet.',
    imaflex2_dual_hap: 'DualLine oder andere Topologien auf imaFlex 2 Dual 100 erfordern ein individuelles VisualApplets-Design als .hap-Datei.',
    acq_only_dll: 'Dies ist ein Acquisition-Framegrabber (nicht programmierbar). Verwenden Sie Standard-.dll-Applets; benutzerdefinierte .hap-Applets werden auf dieser Hardwareklasse nicht unterstützt.',
    imaflex_both: 'imaFlex-Boards sind programmierbare Framegrabber: Sie unterstützen Standard-.dll-Applets und individuelle VisualApplets-.hap-Designs.',
    hap_load: 'Laden Sie ein individuelles VisualApplets-Applet (.hap) auf diesem programmierbaren Framegrabber.',
    hap_name_val: 'VisualApplets-.hap-Name: {name}.',
    scan_area: 'Flächenscan',
    scan_line: 'Linienscan',
    req_complete: 'Liefern Sie ein vollständiges {lang}-Beispiel.',
    req_cmake: 'CMakeLists.txt einschließen.',
    req_error: 'Robuste Fehlerbehandlung implementieren.',
    req_raii: 'RAII oder klar strukturiertes Cleanup verwenden.',
    req_timeout: 'Timeout-Handling implementieren.',
    req_board: 'Board-Erkennung zeigen.',
    req_std_dll: 'Das korrekte Standard-Erfassungs-.dll-Applet laden ({name}).',
    req_std_dll_generic: 'Das korrekte Standard-Erfassungs-.dll-Applet laden (SingleArea, SingleLine, DualArea, DualLine, QuadArea oder QuadLine je nach Anwendung).',
    req_hap: 'Das angegebene VisualApplets-.hap-Applet auf dem programmierbaren Framegrabber laden.',
    req_applet: 'Applet-Laden oder bereits geladenes Applet wie konfiguriert behandeln.',
    req_ports: 'Kamera-/Port-Zuordnung zeigen.',
    req_separate: 'Kamera-Parameter von Framegrabber-/Applet-Parametern trennen.',
    req_buffers: 'Explizite Pufferallokation zeigen.',
    req_dma: 'DMA/Kanäle einrichten.',
    req_device: 'Geräteerkennung und Kameraöffnung zeigen.',
    req_stream: 'Trigger und Stream-Grabber-Handling konfigurieren.',
    req_pylon_buf: 'Angemessenes Puffer-Handling für pylon zeigen.',
    req_acq: 'Expliziten Erfassungsstart und -stopp zeigen.',
    req_loop: 'Erfassungsschleife für mehrere Frames einschließen.',
    req_image: 'Beispiel für Bilddatenzugriff einschließen.',
    req_requeue_fg: 'Puffer-Requeueing einschließen.',
    req_requeue_pylon: 'Entsprechendes Puffer-Handling für pylon einschließen.',
    req_shutdown: 'Alle Ressourcen beim Shutdown freigeben.',
    req_assumptions: 'Annahmen und TODOs explizit auflisten.',
    req_no_hallucinate: 'Keine SDK-APIs erfinden.',
    req_no_pseudo: 'Kein Pseudocode ausgeben, sofern Pseudocode nicht angefordert wurde.',
    req_no_arch: 'Nicht nur Architektur liefern, wenn Code angefordert wurde.',
    req_multi_sync: 'Hinweise zur Multi-Kamera-Synchronisation einbeziehen, wo relevant.',
    warning_final: 'Listen Sie vor dem Schreiben von Code alle Annahmen auf. Wenn ein exakter Basler-SDK-API-Name unsicher ist, erfinden Sie ihn nicht. Markieren Sie ihn als TODO und erklären Sie, was in der offiziellen Dokumentation geprüft werden muss.'
  };

  const KO = Object.assign({}, EN, {
    role_fg: 'Basler Framegrabber SDK, CoaXPress, Camera Link, DMA 버퍼링, 산업용 이미지 획득, 트리거 처리 및 견고한 리소스 정리 경험이 있는 신중한 C++ 개발자입니다.',
    role_pylon: 'Basler pylon SDK, GenICam, 스트림 그래버, 산업용 카메라 획득, 트리거 처리, 버퍼 관리 및 견고한 리소스 정리 경험이 있는 신중한 C++ 개발자입니다.',
    deep_mandatory: '필수: 이 작업 전체에 확장 사고/심층 분석 모드가 활성화되어 있어야 합니다. 시간 절약을 위해 분석을 건너뛰지 마세요.',
    deep_priority: '간결함보다 정확성을 우선하세요. 코드 작성 전에 초기화 순서, 버퍼 수명 주기, 오류 경로 및 종료를 분석하세요.',
    not_provided: '(제공되지 않음)', not_specified: '지정되지 않음', none_detected: '(입력 텍스트에서 감지되지 않음)',
    cfg_sdk_route: 'SDK 경로', cfg_num_cameras: '카메라 수', cfg_hardware: '획득 하드웨어', cfg_hw_class: '하드웨어 클래스',
    warning_final: '코드를 작성하기 전에 모든 가정을 나열하세요. 정확한 Basler SDK API 이름이 불확실하면 만들지 마세요. TODO로 표시하고 공식 문서에서 확인할 내용을 설명하세요.'
  });

  const ZH = Object.assign({}, EN, {
    role_fg: '您是一位谨慎的 C++ 开发者，熟悉 Basler Framegrabber SDK、CoaXPress、Camera Link、DMA 缓冲、工业图像采集、触发处理和稳健的资源清理。',
    role_pylon: '您是一位谨慎的 C++ 开发者，熟悉 Basler pylon SDK、GenICam、流采集器、工业相机采集、触发处理、缓冲管理和稳健的资源清理。',
    deep_mandatory: '强制：整个任务必须启用扩展思考/深度分析模式。不要为节省时间跳过分析。',
    deep_priority: '正确性优先于简洁。在编写代码前分析初始化顺序、缓冲区生命周期、错误路径和关闭流程。',
    not_provided: '（未提供）', not_specified: '未指定', none_detected: '（输入文本中未检测到）',
    cfg_sdk_route: 'SDK 路径', cfg_num_cameras: '相机数量', cfg_hardware: '采集硬件', cfg_hw_class: '硬件类别',
    warning_final: '在编写代码前列出所有假设。若不确定确切的 Basler SDK API 名称，请勿编造。标记为 TODO 并说明须在官方文档中核对的内容。'
  });

  const JA = Object.assign({}, EN, {
    role_fg: 'Basler Framegrabber SDK、CoaXPress、Camera Link、DMA バッファリング、産業用画像取得、トリガー処理、堅牢なリソース解放の経験を持つ慎重な C++ 開発者です。',
    role_pylon: 'Basler pylon SDK、GenICam、ストリームグラバー、産業用カメラ取得、トリガー処理、バッファ管理、堅牢なリソース解放の経験を持つ慎重な C++ 開発者です。',
    deep_mandatory: '必須：このタスク全体で拡張思考／深い分析モードを有効にしてください。時間短縮のため分析を省略しないでください。',
    deep_priority: '簡潔さより正確性を優先してください。コード作成前に初期化順序、バッファライフサイクル、エラーパス、シャットダウンを分析してください。',
    not_provided: '（未入力）', not_specified: '未指定', none_detected: '（入力テキストから検出なし）',
    cfg_sdk_route: 'SDK ルート', cfg_num_cameras: 'カメラ数', cfg_hardware: '取得ハードウェア', cfg_hw_class: 'ハードウェアクラス',
    warning_final: 'コードを書く前にすべての仮定を列挙してください。正確な Basler SDK API 名が不明な場合は推測しないでください。TODO としてマークし、公式ドキュメントで確認すべき内容を説明してください。'
  });

  const VI = Object.assign({}, EN, {
    role_fg: 'Bạn là lập trình viên C++ cẩn thận, có kinh nghiệm với Basler Framegrabber SDK, CoaXPress, Camera Link, DMA buffering, thu thập ảnh công nghiệp, xử lý trigger và giải phóng tài nguyên mạnh.',
    role_pylon: 'Bạn là lập trình viên C++ cẩn thận, có kinh nghiệm với Basler pylon SDK, GenICam, stream grabber, thu thập camera công nghiệp, xử lý trigger và quản lý bộ đệm.',
    deep_mandatory: 'BẮT BUỘC: Chế độ suy luận mở rộng / phân tích sâu PHẢI bật cho toàn bộ tác vụ. Không bỏ qua phân tích để tiết kiệm thời gian.',
    deep_priority: 'Ưu tiên đúng hơn ngắn. Phân tích thứ tự khởi tạo, vòng đời bộ đệm, đường lỗi và shutdown trước khi viết code.',
    not_provided: '(chưa cung cấp)', not_specified: 'chưa chỉ định', none_detected: '(không phát hiện từ văn bản nhập)',
    cfg_sdk_route: 'Tuyến SDK', cfg_num_cameras: 'Số camera', cfg_hardware: 'Phần cứng thu thập', cfg_hw_class: 'Lớp phần cứng',
    warning_final: 'Trước khi viết code, liệt kê mọi giả định. Nếu không chắc tên API Basler SDK, đừng bịa. Đánh dấu TODO và giải thích cần kiểm tra gì trong tài liệu chính thức.'
  });

  global.PROMPT_BODIES = { en: EN, de: DE, ko: KO, zh: ZH, ja: JA, vi: VI };

  global.PROMPT_SECTIONS = {
    en: { role: 'Role', deep_analysis: 'Deep analysis requirement', documentation: 'Documentation requirement', app_desc: 'Application description', workflow: 'Existing acquisition workflow summary', config: 'Selected configuration', topics: 'Detected technical topics', output: 'Required output', warning: 'Warning' },
    de: { role: 'Rolle', deep_analysis: 'Anforderung an tiefe Analyse', documentation: 'Dokumentationsanforderung', app_desc: 'Anwendungsbeschreibung', workflow: 'Zusammenfassung bestehender Erfassungs-Workflow', config: 'Gewählte Konfiguration', topics: 'Erkannte technische Themen', output: 'Erforderliche Ausgabe', warning: 'Warnung' },
    ko: { role: '역할', deep_analysis: '심층 분석 요구사항', documentation: '문서 요구사항', app_desc: '애플리케이션 설명', workflow: '기존 획득 워크플로 요약', config: '선택된 구성', topics: '감지된 기술 주제', output: '필수 출력', warning: '경고' },
    zh: { role: '角色', deep_analysis: '深度分析要求', documentation: '文档要求', app_desc: '应用描述', workflow: '现有采集工作流摘要', config: '所选配置', topics: '检测到的技术主题', output: '必需输出', warning: '警告' },
    ja: { role: '役割', deep_analysis: '深い分析要件', documentation: 'ドキュメント要件', app_desc: 'アプリケーション説明', workflow: '既存取得ワークフロー要約', config: '選択された構成', topics: '検出された技術トピック', output: '必須出力', warning: '警告' },
    vi: { role: 'Vai trò', deep_analysis: 'Yêu cầu phân tích sâu', documentation: 'Yêu cầu tài liệu', app_desc: 'Mô tả ứng dụng', workflow: 'Tóm tắt quy trình thu thập hiện có', config: 'Cấu hình đã chọn', topics: 'Chủ đề kỹ thuật phát hiện', output: 'Đầu ra bắt buộc', warning: 'Cảnh báo' }
  };

})(typeof window !== 'undefined' ? window : globalThis);
